### ISSUE TITLE
P and C client FTA records out of synch in ref_client.

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-api#100]
scripts/import.js pulls in client records from FTA, but the source query for that endpoint excludes 'P' and 'C' records.  These are 'not active' for our intents and purposes and we need to:

1.  Get them included in the query so we can update them on our end (They just need confirmation from us that we are ready, I've filled out all the paperwork).
2.  Make sure we filter these records when looking for the active agreement holders/signatories (this issue)

Separate, but equally annoying to staff as #90.

@calebissharp big win if we can sort this one out in 2019.  Here's what the range client import endpoint import.js looks for looks like (but with much less data).

{
    "items": [
        {
            "forest_file_id": "RAN09999",
            "client_number": "00001023",
            "client_locn_code": "00",
            "client_name": "MARTIN, STEVE",
            "forest_file_client_type_code": "A",
            "licensee_start_date": "2009-02-06T08:00:00Z",
            "licensee_end_date": null
        },
        {
            "forest_file_id": "RAN09998",
            "client_number": "00001024",
            "client_locn_code": "00",
            "client_name": "Banana RANCH LTD.",
            "forest_file_client_type_code": "P",
            "licensee_start_date": null,
            "licensee_end_date": null
        }
]
}

**Comment by micheal-w-wells** [comment]
moving this to in progress as I'm asking ORDS group to update query in dev/test but the code portion of this is up for grabs

**Comment by micheal-w-wells** [comment]
was approved yesterday, pending notification from dba

**Comment by micheal-w-wells** [comment]
Poked DBA today to see if we can get this in to dev ASAP, we have approvals at this point but the dates i asked for have since past.  Will call DBA tomorrow if i don't hear back.

**Comment by micheal-w-wells** [comment]
Unblocking as this is supposedly happening on Monday the 13th in test.

**Comment by micheal-w-wells** [comment]
Update applied but our creds aren't working in dev, I have requested a reset then I will run the FTA jobs in test.

**Comment by micheal-w-wells** [comment]
Ok we can login and the query is update.  Wow.

Now comes the running of the import job.  Tried to run against test but got an error, searched the source code AND the input file and couldn't fine the string being referenced.  @calebissharp is this ringing any bells for you that it isn't for me?


`Error with message = total_non_use is not defined, usage year 1992 row: 195
Error importing data, message = total_non_use is not defined`

**Comment by micheal-w-wells** [comment]
`total_non _use` is in the usage.js model in /libs/db2 and it is a column in the db and it isn't referenced in import.js.  Missing something obvious going to come back to this one.

**Comment by calebissharp** [comment]
@micheal-w-wells This is what I fixed before: https://github.com/bcgov/range-api/pull/110/files#diff-70f0920193b81c3f6e43aa3eac9d69c2. Maybe you're using an older version of the repo?

**Comment by micheal-w-wells** [comment]
@calebissharp I think I ran 'npm run build' in the wrong tmux window, gonna try again right now

**Comment by micheal-w-wells** [comment]
RAN076364 in Test looks good to me.  It will have to be the test instance of FTA if you want to see what it looks like there, otherwise I can do a dump of ref_client.  I have also slack'd the list as it comes over from test FTA (filtered for just that RAN) to Lisa.  

We might want to really look at blowing away the test db because we have RANS now from two instances of FTA and I'm not sure where they overlap.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 I think we are good to push that query update to ORDS in prod based on test with RAN070592.  I think if there are statuses other than A B P and C we should add those too otherwise they will have the same issue.

**Comment by micheal-w-wells** [comment]
OK so we nailed down the new version of the ORDS query is good but there's still an issue with the import related to client_agreement.  Stand by.

**Comment by micheal-w-wells** [comment]
https://web-range-myra-test.pathfinder.gov.bc.ca/range-use-plan/175

If you have a couple more RANS you want to test it out on, give it a day for data to make the hop from test FTA to test ORDS, then I'll run the job again.

**Comment by micheal-w-wells** [comment]
This is live and going to be all done when the ORDS people do their jam on Thurs.  Closing.
